name: update-readme

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'README.md'
    - 'test/README.md'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Token generator
      uses: githubofkrishnadhas/github-access-using-githubapp@v2
      id: token-generation
      with:
        github_app_id: ${{ secrets.TOKEN_GENERATOR_APPID }}
        github_app_private_key: ${{ secrets.TOKEN_GENERATOR_PRIVATE_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        token: ${{ steps.token-generation.outputs.token }}
        fetch-depth: 0
        persist-credentials: true

    - name: Install tree utility
      run: |
        sudo apt-get update
        sudo apt-get install -y tree

    - name: Generate and inject folder tree
      run: |
        set -e
        tree_output=$(tree -I ".git|.github|__pycache__|*.pyc" -a)
        escaped_tree=$(printf '%s\n' "$tree_output")
        awk -v new_content="$escaped_tree" '
          /<!-- BEGIN_REPO_TREE -->/ { print; print "```"; print new_content; print "```"; in_block=1; next }
          /<!-- END_REPO_TREE -->/ { in_block=0 }
          !in_block
        ' README.md > README.tmp && mv README.tmp README.md

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.4.1
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "false"
    - name: list files
      run: |
        ls -la
        sudo chown -R $USER:$USER .

    - name: Commit and push changes
      run: |
        git status
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "docs: update README" || echo "No changes to commit"
        git pull --rebase origin main || true
        git push origin main
